"""Added Flask Login and other new features

Revision ID: 376f62504033
Revises: 31d75408007e
Create Date: 2020-05-10 21:33:34.288220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376f62504033'
down_revision = '31d75408007e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
