"""empty message

Revision ID: d64cb3258368
Revises: 376f62504033
Create Date: 2020-05-26 21:51:46.772852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64cb3258368'
down_revision = '376f62504033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo_list', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.drop_column('todo_list', 'user_id')
    # ### end Alembic commands ###
